local describe = require("lib.test")
local p2 = require(".2024.08.p2")

describe("input", function(it)
it("example 1", function()
    local example = [[T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........]]
    local expected = 9

    local n = p2.solve(example)

    assert(n == expected, string.format("Expected %d, but was %d", expected, n))
  end)

  it("example 1", function()
    local example = [[............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............]]
    local expected = 34

    local n = p2.solve(example)

    assert(n == expected, string.format("Expected %d, but was %d", expected, n))
  end)

  it("input", function()
    local fp = io.open("./2024/08/assets/input.txt", "r") or error("Input not found")
    local input = fp:read("*a")
    local expected = 1005

    local n = p2.solve(input)

    assert(n == expected, string.format("Expected %d, but was %d", expected, n))
  end)
end)
